version: '3'

services:

  # prod config
  nginx: 
    image: nginx:latest
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy/htpasswd:/etc/nginx/htpasswd
      - /etc/letsencrypt/live/platspinnen.swedencentral.cloudapp.azure.com/fullchain.pem:/etc/nginx/certs/fullchain.pem
      - /etc/letsencrypt/live/platspinnen.swedencentral.cloudapp.azure.com/privkey.pem:/etc/nginx/certs/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    depends_on:
      - backend
      - frontend

  # localhost config
  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./proxy/default_dev.conf:/etc/nginx/conf.d/default.conf
  #     - ./proxy/htpasswd:/etc/nginx/htpasswd
  #   ports:
  #     - "8082:80"
  #   depends_on:
  #     - backend
  #     - frontend

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: pp-db-user
      POSTGRES_PASSWORD: pp-db-pass
      POSTGRES_DB: platspinnendb
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/platspinnendb
      SPRING_DATASOURCE_USERNAME: pp-db-user
      SPRING_DATASOURCE_PASSWORD: pp-db-pass
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "85:80"
    restart: unless-stopped
    depends_on:
      - backend
      - postgres

volumes:
  postgres-data:
